### ISSUE TITLE
Results in a document

### ISSUE THREAD

**Issue by marciotrindade** [leonid-shevtsov/SearchInProject_SublimeText#6]
Can I have the results in a new document like the default search of Sublime?

Tank you

**Comment by leonid-shevtsov** [comment]
I've been laying off this feature because right now there is no way to open the native Find Results view through the API.

I made a draft implementation in the find-results-buffer branch, and it does generate a buffer that looks almost like the Find Results view, but not quite, and the most glaring difference is that file paths are not clickable.

I don't want to make a half-assed feature, so this will have to wait for some progress on the Sublime Text side.

**Comment by Leimi** [comment]
Thanks for the explanation.

**Comment by leonid-shevtsov** [comment]
I had come up on a different use case for this feature - to basically filter files rather than searching - and this use case doesn't require navigation.

So, I've released a "List results in view" feature in the new 1.6.0 release.

Suggestions are welcome.

**Comment by dtaub** [comment]
Thanks for the feature. It seems though, that there's a bug causing there to always be a result missing from the buffer view.

**Comment by leonid-shevtsov** [comment]
@dtaub thanks for noticing! I've released version 1.6.2 with a fix.
